In [1]:
import numpy


In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
import numpy as np

In [4]:
a=np.array(10)

In [5]:
print(a)

10


In [6]:
# 1 dimensional arrays
a=np.array([10,20,30])

In [7]:
print(a)

[10 20 30]


In [8]:
#2 dimensional arrays
a=np.array([[10,20],[30,40]])
print(a)

[[10 20]
 [30 40]]


In [9]:
import numpy as np
#3-dimensional arrays
a=np.array([[[10,20],[30,40]],[[50,60],[50,60]],[[70,80],[90,10]]])
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [50 60]]

 [[70 80]
  [90 10]]]


In [10]:
print(a)

[[[10 20]
  [30 40]]

 [[50 60]
  [50 60]]

 [[70 80]
  [90 10]]]


In [15]:
a[1,0,0]

50

In [23]:
a[0][1][1]

40

In [14]:
a[2][2]

8

In [16]:
a=([10,20,30])
b=np.array(a,dtype=float)
print(b)

[10. 20. 30.]


In [32]:
a=[[10,20],[30,40]]
b=np.array(a,dtype=int,order="c")
print(b)

[[10 20]
 [30 40]]


In [34]:
for i in np.nditer(b):
    print(i)

10
20
30
40


In [36]:
a=[[10,20],[30,40]]
b=np.array(a,dtype=int,order="F")
print(b)

[[10 20]
 [30 40]]


In [37]:
for i in np.nditer(b):
    print(i)

10
30
20
40


In [17]:
for j in np.nditer(a):
    print(j)

(array(10), array(20), array(30))


In [38]:
print(b)

[[10 20]
 [30 40]]


In [39]:
a=b"welcome to numpy"

In [42]:
np.frombuffer(a,dtype="S1")

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o', b' ',
       b'n', b'u', b'm', b'p', b'y'], dtype='|S1')

In [43]:
np.frombuffer(a,dtype="S1",count=10)

array([b'w', b'e', b'l', b'c', b'o', b'm', b'e', b' ', b't', b'o'],
      dtype='|S1')

In [47]:
np.frombuffer(a,dtype="S1",offset=9)

array([b'o', b' ', b'n', b'u', b'm', b'p', b'y'], dtype='|S1')

In [48]:
np.frombuffer(a,dtype="S1",count=2,offset=9)

array([b'o', b' '], dtype='|S1')

In [16]:
import numpy as np
a=np.arange(16).reshape(2,4,2)
#a2=np.arange(9).reshape
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [26]:
import numpy as np
z=np.arange(4).reshape()
print(z)

ValueError: cannot reshape array of size 10 into shape (0,)

In [51]:
np.fromiter(a,dtype=int,count=3)

array([10, 20, 30])

In [1]:
l=[1,2,3,4]
l2=[3,4,5]
print(l+l2)

[1, 2, 3, 4, 3, 4, 5]


In [7]:
#iterate 3d matricx
#how to write covert into degree
#upper traingl,a matrix skipping zero