In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3,4,5])

In [3]:
array1

array([1, 2, 3, 4, 5])

In [4]:
array1

array([1, 2, 3, 4, 5])

In [5]:
array1.ndim

1

In [6]:
array2=np.array([[1,2,3,4,5],[3,4,5,6,7]])

In [7]:
array2

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [8]:
array2.ndim

2

In [9]:
array3=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])

In [10]:
array3

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [6]:
import numpy as np
x=np.array([[[[1,2],[3,4]],[[4,5],[6,7]]],[[[1,2],[3,4]],[[4,5],[6,7]]]])

In [7]:
x.ndim

4

In [ ]:
x=np.array()

In [12]:
array4=np.arange(10)

In [13]:
array4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
array5=np.arange(10,20)

In [15]:
array5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
array6=np.arange(10,20,3)

In [17]:
array6

array([10, 13, 16, 19])

In [18]:
a=np.zeros(5)

In [19]:
a

array([0., 0., 0., 0., 0.])

In [22]:
b=np.zeros((3,3))

In [23]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [24]:
c=np.zeros((2,3))

In [25]:
c

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a1=np.ones(5)

In [27]:
a1

array([1., 1., 1., 1., 1.])

In [12]:
import numpy as np
b1=np.ones((3,3))

In [13]:
b1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
a3=np.eye(3)

In [16]:
a3*5

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

In [4]:
import numpy as np



In [8]:
p=5*np.ones((3,3))

In [9]:
p

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [17]:
v=np.diag([2,3,4])

In [18]:
v

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [11]:
c=np.diag([1,2,3,4,5])
c2=np.diag([3,4,5,6,7])

In [12]:
c*c2

array([[ 3,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0,  0, 24,  0],
       [ 0,  0,  0,  0, 35]])

In [14]:
c.dot(c2)

array([[ 3,  0,  0,  0,  0],
       [ 0,  8,  0,  0,  0],
       [ 0,  0, 15,  0,  0],
       [ 0,  0,  0, 24,  0],
       [ 0,  0,  0,  0, 35]])

In [3]:
list1=[[2,3],[6,7]]
list2=[[1,2],[3,4]]
print(list1+list2)

[[2, 3], [6, 7], [1, 2], [3, 4]]


In [4]:
def fun(l1,l2):
    return l1+l2
l1=[1,2,3]
l2=[3,4,5]
fun(l1,l2)

[1, 2, 3, 3, 4, 5]

In [2]:
list1=[[1,2],[3,4]]
list2=[[2,3],[5,6]]
result=[[0,0],[0,0]]
for i in range(len(list1)):
    for j in range(len(list2)):
        result[i][j]=list1[i][j]+list2[i][j]
print(result)

[[3, 5], [8, 10]]


In [14]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[5,6]])
print(a+b)

[[ 3  5]
 [ 8 10]]


In [15]:
list1=[[1,2],[3,4]]
list2=[[2,3],[5,6]]
result=[[0,0],[0,0]]
for i in range(len(list1)):
    for j in range(len(list2)):
        for k in range(len(list2)):
            result[i][j]+=list1[i][k]*list2[k][j]
print(result)

[[12, 15], [26, 33]]


In [16]:
list1=np.array([[1,2],[3,4]])
list2=np.array([[2,3],[5,6]])

In [17]:
list1*list2

array([[ 2,  6],
       [15, 24]])

In [18]:
list1.dot(list2)

array([[12, 15],
       [26, 33]])

In [20]:
c=5*np.ones((3,3))

In [21]:
c

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [23]:
array3=np.diag([1,3,4,6,5])

In [24]:
array3

array([[1, 0, 0, 0, 0],
       [0, 3, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 6, 0],
       [0, 0, 0, 0, 5]])

In [26]:
array1=np.diag([1,3,4,6,5])
array2=np.diag([4,5,6,7,8])

In [27]:
print(array1*array2)

[[ 4  0  0  0  0]
 [ 0 15  0  0  0]
 [ 0  0 24  0  0]
 [ 0  0  0 42  0]
 [ 0  0  0  0 40]]


In [26]:
l=np.linspace(0,1) #this is automatically stop without 

In [27]:
l

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [31]:
l=np.linspace(0,1,5)

In [32]:
l

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
l=np.linspace(10,20,10)
print(l)

[10.         11.11111111 12.22222222 13.33333333 14.44444444 15.55555556
 16.66666667 17.77777778 18.88888889 20.        ]


In [35]:
r1=np.random.rand(5)
print(r1)

[0.99791092 0.1296708  0.99392741 0.48075005 0.01968258]


In [36]:
r1=np.random.rand(5)
print(r1)

[0.00551805 0.5140066  0.36111785 0.62112198 0.23081923]


In [38]:
 #Gaussian distribution
r2=np.random.randn(5)
print(r2)

[ 0.46362318 -0.33710258 -1.25211618 -0.10243276 -1.7264473 ]


In [39]:
p=np.array([1,2,3,4])
q=p.copy()
print(q)

[1 2 3 4]


In [40]:
a1=np.array([1,2,3,4,5])

In [41]:
a1.ndim

1

In [42]:
a1.shape

(5,)

In [43]:
a2=np.array([[[1,2],[2,3]],[[4,5],[7,8]]])

In [44]:
a2.shape

(2, 2, 2)

In [1]:
import numpy as np

In [2]:
a=np.random.rand(3,3)

In [3]:
a

array([[0.50669219, 0.86349396, 0.71246276],
       [0.88080764, 0.49290233, 0.82347787],
       [0.63407946, 0.3286441 , 0.71783558]])

In [4]:
b=np.random.randn(3,3)

In [5]:
b

array([[-0.80771703, -0.15512943, -0.1092857 ],
       [-0.99271067,  1.17359664,  0.21352128],
       [ 0.05838072, -0.18476412, -0.8542729 ]])

In [17]:
c=np.random.randint(10,20,(3,3))
print(c)

[[12 17 13]
 [15 17 15]
 [19 18 14]]


In [8]:
c

array([[12, 10, 10],
       [15, 10, 17],
       [19, 10, 10]])

In [10]:
c.ndim

2

In [11]:
c.shape

(3, 3)

In [12]:
x=np.array([1,2,3,4,5])

In [13]:
x.shape

(5,)

In [14]:
c.size

9

In [15]:
c

array([[12, 10, 10],
       [15, 10, 17],
       [19, 10, 10]])

In [18]:
c.itemsize

4

In [19]:
c.dtype

dtype('int32')

In [21]:
c.astype('float')

array([[12., 17., 13.],
       [15., 17., 15.],
       [19., 18., 14.]])

In [22]:
a=np.array([[1,2],[4,5]])
b=np.array([[4,5],[3,4]])

In [23]:
a+b

array([[5, 7],
       [7, 9]])

In [24]:
a-b

array([[-3, -3],
       [ 1,  1]])

In [25]:
a*b

array([[ 4, 10],
       [12, 20]])

In [26]:
a.dot(b)

array([[10, 13],
       [31, 40]])

In [32]:
p=([[1,2,3],[3,5,6]])
trace=0
for i in range(len(p)):
    for j in range(len(p)):
        if i==j:
            trace+=p[i][j]
print(trace)

6


In [33]:
np.trace(p)

6

In [34]:
mat=np.array([[1,2],[3,4]])

In [35]:
mat

array([[1, 2],
       [3, 4]])

In [36]:
np.linalg.inv(mat)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [19]:
mat1=[[1,2,3],[4,7,9],[11,9,23]]
k=11
for i in range(len(mat1)):
    for j in range(len(mat1)):
        if k==mat1[i][j]:
            print("element found")

element found


In [40]:
c

array([[12, 17, 13],
       [15, 17, 15],
       [19, 18, 14]])

In [41]:
np.linalg.det(c)

201.9999999999999

In [42]:
c

array([[12, 17, 13],
       [15, 17, 15],
       [19, 18, 14]])

In [43]:
np.linalg.matrix_rank(c)

3

In [44]:
s=np.array([2,3,4,5,6])

In [45]:
s+1

array([3, 4, 5, 6, 7])

In [46]:
s-1

array([1, 2, 3, 4, 5])

In [47]:
s*2

array([ 4,  6,  8, 10, 12])

In [48]:
s**2

array([ 4,  9, 16, 25, 36])

In [50]:
a1=np.array([2,3,4,5])
a2=np.array([6,7,8,9])

In [51]:
a1>a2

array([False, False, False, False])

In [52]:
a1<a2

array([ True,  True,  True,  True])

In [53]:
a1==a2

array([False, False, False, False])

##22/03/2025:

In [36]:
import numpy as np

In [37]:
a=np.array([2,3,4,5,6])
b=np.array([4,5,6,7,8])

In [3]:
a+b

array([ 6,  8, 10, 12, 14])

In [4]:
a-b

array([-2, -2, -2, -2, -2])

In [5]:
a*b

array([ 8, 15, 24, 35, 48])

In [6]:
b/a

array([2.        , 1.66666667, 1.5       , 1.4       , 1.33333333])

In [7]:
a//b

array([0, 0, 0, 0, 0])

In [8]:
a%b

array([2, 3, 4, 5, 6])

In [9]:
a**b

array([     16,     243,    4096,   78125, 1679616])

In [10]:
array1=np.array([3,4,5,6,7])

In [11]:
array1+1

array([4, 5, 6, 7, 8])

In [12]:
array1-3

array([0, 1, 2, 3, 4])

In [13]:
array1*4

array([12, 16, 20, 24, 28])

In [14]:
array1**2

array([ 9, 16, 25, 36, 49])

In [15]:
a

array([2, 3, 4, 5, 6])

In [16]:
b

array([4, 5, 6, 7, 8])

In [17]:
a<b

array([ True,  True,  True,  True,  True])

In [18]:
a>b

array([False, False, False, False, False])

In [19]:
a!=0

array([ True,  True,  True,  True,  True])

In [20]:
a1=np.array([2,3,4,5])
a2=np.array([4,5,6,7])
a3=np.array([2,3,4,5])

In [21]:
np.array_equal(a1,a2)

False

In [24]:
np.array_equal(a1,a3)

True

In [25]:
np.logical_and(a,b)

array([ True,  True,  True,  True,  True])

In [26]:
np.logical_or(a,b)

array([ True,  True,  True,  True,  True])

In [27]:
a

array([2, 3, 4, 5, 6])

In [28]:
np.all(a)

True

In [35]:
p=np.array([0,2,3,4,5])

In [36]:
np.all(p)

False

In [37]:
np.any(p)

True

In [38]:
s=np.zeros(4)

In [39]:
s

array([0., 0., 0., 0.])

In [40]:
s=s.astype('int')

In [41]:
s

array([0, 0, 0, 0])

In [42]:
np.any(s)

False

In [43]:
a

array([2, 3, 4, 5, 6])

In [44]:
np.sin(a)

array([ 0.90929743,  0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [47]:
arr=np.array([90,4,5,45,30])

In [48]:
np.sin(arr)

array([ 0.89399666, -0.7568025 , -0.95892427,  0.85090352, -0.98803162])

In [49]:
arr

array([90,  4,  5, 45, 30])

In [50]:
np.log(arr)

array([4.49980967, 1.38629436, 1.60943791, 3.80666249, 3.40119738])

In [51]:
np.exp(arr)

array([1.22040329e+39, 5.45981500e+01, 1.48413159e+02, 3.49342711e+19,
       1.06864746e+13])

In [52]:
np.sum(arr)

174

In [53]:
np.min(arr)

4

In [54]:
np.max(arr)

90

In [55]:
np.argmax(arr)

0

In [56]:
np.argmin(arr)

1

In [57]:
len(arr)

5

In [58]:
arr

array([90,  4,  5, 45, 30])

In [59]:
aa=np.array([-3,-34,67,44,-2,56,77,-100])

In [60]:
bb=np.sort(aa)

In [61]:
aa

array([  -3,  -34,   67,   44,   -2,   56,   77, -100])

In [62]:
bb

array([-100,  -34,   -3,   -2,   44,   56,   67,   77])

In [63]:
cc=np.argsort(aa)

In [64]:
cc

array([7, 1, 0, 4, 3, 5, 2, 6], dtype=int64)

In [65]:
aa

array([  -3,  -34,   67,   44,   -2,   56,   77, -100])

In [66]:
aa.sort()

In [67]:
aa

array([-100,  -34,   -3,   -2,   44,   56,   67,   77])

In [68]:
x=np.array([[10,-77,0],[-22,34,-88],[5,-34,45]])

In [69]:
x

array([[ 10, -77,   0],
       [-22,  34, -88],
       [  5, -34,  45]])

In [70]:
y=np.sort(x)

In [71]:
y   #roles is sort

array([[-77,   0,  10],
       [-88, -22,  34],
       [-34,   5,  45]])

In [72]:
y

array([[-77,   0,  10],
       [-88, -22,  34],
       [-34,   5,  45]])

In [73]:
z=np.sort(x,axis=0)

In [74]:
z  #this is column sort

array([[-22, -77, -88],
       [  5, -34,   0],
       [ 10,  34,  45]])

In [13]:
import numpy as np
a1=np.array([2,3,4,5])
a2=np.array([4,5,6,7])
a=np.concatenate((a1,a2))
print(a)

[2 3 4 5 4 5 6 7]


In [14]:
import numpy as np

In [25]:
a1=np.array([0,1,2,3,4,5,6])

In [26]:
a1[3:]=10

In [27]:
a1

array([ 0,  1,  2, 10, 10, 10, 10])

In [47]:
a=np.arange(10)
b=np.array([100,120,140,150])
c=np.concatenate((a[:7:],b[::-1]))

In [48]:
c

array([  0,   1,   2,   3,   4,   5,   6, 150, 140, 120, 100])

In [29]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 24/03/2025

In [1]:
import numpy as np

In [2]:
a=np.array([34,-8,90,-67,23,46,-71,89,4])

In [3]:
b=np.sort(a)

In [4]:
b

array([-71, -67,  -8,   4,  23,  34,  46,  89,  90])

In [5]:
c=np.sort(a)[::-1]

In [6]:
c

array([ 90,  89,  46,  34,  23,   4,  -8, -67, -71])

In [9]:
d=np.argsort(a) #sort in length wise

In [10]:
d

array([6, 3, 1, 8, 4, 0, 5, 7, 2], dtype=int64)

In [12]:
d=np.argsort(a)[::-1]

In [13]:
d

array([2, 7, 5, 0, 4, 8, 1, 3, 6], dtype=int64)

In [14]:
p=np.array([34,-8,90,-67,23,46,-71,89,4])

In [15]:
np.where (p>5) #length wise

(array([0, 2, 4, 5, 7], dtype=int64),)

In [16]:
np.where(p==5)

(array([], dtype=int64),)

In [17]:
np.where(p<2)

(array([1, 3, 6], dtype=int64),)

In [1]:
q=np.array([3,4,5,6,70,0,9,12])

In [2]:
np.nonzero(q)

(array([0, 1, 2, 3, 4, 6, 7], dtype=int64),)

In [3]:
np.extract(q>4,q) 

array([ 5,  6, 70,  9, 12])

In [22]:
array1=np.array([3,4,5,6,7])

In [23]:
np.append(array1,[34,56])

array([ 3,  4,  5,  6,  7, 34, 56])

In [24]:
array2=np.append(array1,[45,67,88])

In [25]:
array2

array([ 3,  4,  5,  6,  7, 45, 67, 88])

In [26]:
array1

array([3, 4, 5, 6, 7])

In [27]:
np.insert(array1,2,100) 

array([  3,   4, 100,   5,   6,   7])

In [28]:
array1[2]

5

In [29]:
array1[3]

6

In [30]:
array1[1:5]

array([4, 5, 6, 7])

In [31]:
aa=np.arange(10)

In [32]:
aa[5:]=10

In [33]:
aa

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [34]:
a1=np.arange(10)

In [35]:
b1=np.arange(5)

In [36]:
a1[5:]=b1[::-1]

In [37]:
a1

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [38]:
a1[3]=1000

In [39]:
a1

array([   0,    1,    2, 1000,    4,    4,    3,    2,    1,    0])

In [40]:
a1

array([   0,    1,    2, 1000,    4,    4,    3,    2,    1,    0])

In [41]:
bb=np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(12,1)

In [42]:
bb

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0]])

In [43]:
bb=np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(4,3)

In [44]:
bb

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 1, 0]])

In [5]:
import numpy as np 
bb=np.array([0,0,0,0,0,0,0,0,0,0,1,0]).reshape(6,2)

In [6]:
bb

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [1, 0]])

### 26/03/2025:

In [8]:
import numpy as np

In [9]:
import pandas as pn

In [10]:
a=pn.array([1,2])

In [11]:
a

<IntegerArray>
[1, 2]
Length: 2, dtype: Int64

In [12]:
import numpy as np

In [13]:
a=np.array([3,4,5,6,7,8,9,10])
for  i in a:
    print(i)

3
4
5
6
7
8
9
10


In [17]:
import numpy as np

In [25]:
b=np.random.randint(5,20,(4,5)).reshape(5,4)

In [27]:
b

array([[10,  5,  8, 12],
       [11,  8,  5,  9],
       [11, 11, 13, 19],
       [19, 18, 14, 15],
       [ 5, 12, 19, 17]])

In [28]:
for i in range(len(b)):
    print(i)

0
1
2
3
4


In [34]:
#rows wise:
for i in range(len(b)):
    for j in range(len(b[i])):
        print(b[i][j])

10
5
8
12
11
8
5
9
11
11
13
19
19
18
14
15
5
12
19
17


In [37]:
for i in range(len(b[0])):  # Iterate over columns (length of first row)
    for j in range(len(b)):  # Iterate over rows
        print(b[j][i], end=" ")  # Print elements in the same column
    print()

10 11 11 19 5 
5 8 11 18 12 
8 5 13 14 19 
12 9 19 15 17 


In [38]:
for i in b.T:  
    print(*i)

10 11 11 19 5
5 8 11 18 12
8 5 13 14 19
12 9 19 15 17


In [40]:
b.shape

(5, 4)

In [41]:
len(b)

5

In [43]:
len(b[0])

4

In [44]:
b.shape[1]

4

In [45]:
c=np.random.randint(1,30,(3,3,3))

In [46]:
c

array([[[ 5,  8, 13],
        [17, 17, 20],
        [15, 22, 16]],

       [[13,  3, 10],
        [23, 22, 24],
        [12, 15, 18]],

       [[ 1,  4,  3],
        [26,  6, 11],
        [10, 29,  3]]])

In [50]:
b[[0,4]]

array([[10,  5,  8, 12],
       [ 5, 12, 19, 17]])

In [1]:
import numpy as np

In [2]:
c=np.array([2,3,4,5,6])

In [3]:
np.cumsum(c)

array([ 2,  5,  9, 14, 20])

In [6]:
b=np.random.randint(5,20,(4,5)).reshape(5,4)

In [7]:
b


array([[18, 19, 11, 11],
       [17, 13, 17, 15],
       [ 8, 15,  6, 16],
       [ 5, 12,  5,  7],
       [10,  5, 13, 18]])

In [8]:
b>15

array([[ True,  True, False, False],
       [ True, False,  True, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False,  True]])

In [10]:
mask=((b>15)&(b%2==0))

In [11]:
mask

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False,  True]])

In [12]:
b[mask]

array([18, 16, 18])

In [13]:
a1=np.arange(9).reshape(3,3)+4

In [14]:
a1

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
aa1=np.arange(8).reshape(2,4)
aa2=np.arange(8,16).reshape(4,2)

In [16]:
aa1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [17]:
aa2

array([[ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [18]:
aa1+aa2

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [19]:
aa3=np.arange(9).reshape(3,3)
aa4=np.arange(3).reshape(3,1)

In [20]:
aa3+aa4

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [21]:
aa5=np.arange(9).reshape(3,3)
aa6=np.arange(3)

In [22]:
aa5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
aa6

array([0, 1, 2])

In [24]:
aa5+aa6

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [25]:
aa7=np.arange(16).reshape(4,4)
aa8=np.arange(9).reshape(3,3)

In [26]:
aa7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [27]:
aa8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
aa7+aa8

ValueError: operands could not be broadcast together with shapes (4,4) (3,3) 

In [29]:
aa9=np.arange(12).reshape(4,3)
aa10=np.arange(3).reshape(3,1)

In [30]:
aa9

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
aa10

array([[0],
       [1],
       [2]])

In [32]:
aa9+aa10

ValueError: operands could not be broadcast together with shapes (4,3) (3,1) 

In [33]:
aa12=np.arange(12)[::-1].reshape(4,3)
aa13=np.arange(1).reshape(1,1)

In [34]:
aa12

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [35]:
aa13

array([[0]])

In [36]:
aa12+aa13

array([[11, 10,  9],
       [ 8,  7,  6],
       [ 5,  4,  3],
       [ 2,  1,  0]])

In [37]:
aa14=np.arange(16).reshape(2,4,2)
aa15=np.arange(3).reshape(3,1)

In [38]:
aa14+aa15

ValueError: operands could not be broadcast together with shapes (2,4,2) (3,1) 

In [39]:
aa16=np.arange(12).reshape(2,2,3)
aa17=np.arange(6).reshape(1,2,3)

In [40]:
aa16+aa17

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[ 6,  8, 10],
        [12, 14, 16]]])

### 27/03/2025

In [4]:
import numpy as np

In [5]:
a=np.arange(9).reshape(3,3)

In [6]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.reshape(a,(1,9),'c') 

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [9]:
np.reshape(a,(1,9),'F')

array([[0, 3, 6, 1, 4, 7, 2, 5, 8]])

In [10]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])

In [12]:
np.concatenate((m1,m2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [13]:
np.hstack((m1,m2)) #horjentally stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [14]:
np.vstack((m1,m2)) 

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [16]:
b=np.array([1,2,3,4,5])
c=b.copy()   #b values in no change
c[0]=1000
print(b)
print(c)

[1 2 3 4 5]
[1000    2    3    4    5]


In [17]:
b

array([1, 2, 3, 4, 5])

In [18]:
d=np.array([5,6,7,8,9])
e=d.view()  #d values in automatically change
e[1]=500
print(d)
print(e)

[  5 500   7   8   9]
[  5 500   7   8   9]


In [19]:
d1=np.arange(16).reshape(4,4)

In [20]:
c1=d1.flatten()

In [21]:
c1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [23]:
c2=d1.ravel()

In [24]:
c2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [25]:
c1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
c2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [28]:
c1[4]=2000

In [29]:
c1

array([   0,    1,    2,    3, 2000,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15])

In [30]:
d1 #this is not change like copy

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
c2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
c2[2]=500

In [33]:
c2

array([  0,   1, 500,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [34]:
d1# this is automaticaly change like view

array([[  0,   1, 500,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [35]:
aa1=np.arange(8).reshape(4,2)

In [36]:
aa1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [39]:
aa2=aa1.T.reshape(4,2)

In [41]:
aa2

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [44]:
np.shares_memory(aa1,aa2)

False

In [45]:
np.shares_memory(aa1,aa2)

False

In [47]:
aa3=np.array([1,2,3,4,5])

In [48]:
aa4=aa3[::2]

In [49]:
aa4

array([1, 3, 5])

In [51]:
np.shares_memory(aa3,aa4)

True

In [56]:
aa5=aa3[::2].copy()

In [57]:
aa5

array([1, 3, 5])

In [59]:
np.shares_memory(aa3,aa5)

False

In [60]:
np.shares_memory(aa3,aa5) # this is return true or sumtimes false

False

In [13]:
k=np.array(([1,2,3],[3,4,5],[6,7,8]))

In [14]:
k

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
r1=np.rot90((k)) #this is 90 degrees rotate

In [16]:
r1

array([[3, 5, 8],
       [2, 4, 7],
       [1, 3, 6]])

In [19]:
r2= np.rot90(k,k=2) #this is 180 degree rotete
print(r2)


[[8 7 6]
 [5 4 3]
 [3 2 1]]


In [83]:
r3=np.flipud(k.T)
print(r3) #this 90 degree

[[3 5 8]
 [2 4 7]
 [1 3 6]]


In [86]:
r3= np.flipud(np.fliplr(k))
print(r3) #this is 180 degrees

[[8 7 6]
 [5 4 3]
 [3 2 1]]


In [87]:
k = [[1, 2, 3], 
     [3, 4, 5], 
     [6, 7, 8]]


In [88]:
k

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [89]:
k

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [90]:
a=len(k) #this is rows
print(a)

3


In [91]:
b=len(k[0])  #this is culomns
print(b)

3


In [102]:
def rotetin_matrix(k):
    r,c=len(k),len(k[0])              #this is without predefine functions in numpy print-90 degree matrix
    rotet=[[0]*r for i in range(c)]
    for i in range(r):
       for j in range(c):
           rotet[j][r-1-i]=k[i][j]
    return rotet 
k = [
    [1, 2, 3], 
    [3, 4, 5], 
    [6, 7, 8]
]
rotetin_matrix=rotetin_matrix(k)
for r in rotetin_matrix:
    print(r)

[6, 3, 1]
[7, 4, 2]
[8, 5, 3]


In [11]:
a=np.array(([1,2,3],[3,4,5],[6,7,8]))
print(a)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [13]:
a[1]

array([3, 4, 5])

In [103]:
def rotetin_matrix(k):
    r,c=len(k),len(k[0])              #this is without predefine functions in numpy print-180 degree matrix
    rotet=[[0]*r for i in range(c)]
    for i in range(r):
       for j in range(c):
           rotet[r-1-i][c-1-j]=k[i][j]
    return rotet 
k = [
    [1, 2, 3], 
    [3, 4, 5], 
    [6, 7, 8]
]
rotetin_matrix=rotetin_matrix(k)
for r in rotetin_matrix:
    print(r)

[8, 7, 6]
[5, 4, 3]
[3, 2, 1]


In [104]:
def rotate_180(k):
    return [row[::-1] for row in k[::-1]]
rotated_180 = rotate_180(k)
for i in rotated_180:
    print(i)

[8, 7, 6]
[5, 4, 3]
[3, 2, 1]


In [107]:
def rotate_90(k):
    return [[k[i][j] for i in range(len(k))][::-1] for j in range(len(k[0]))]

# Given Matrix
k = [
    [1, 2, 3], 
    [3, 4, 5], 
    [6, 7, 8]
]

# Rotate 90 degrees counterclockwise
rotated_90 = rotate_90(matrix)

# Print result
for  in rotated_90:
    print(row)


[6, 3, 1]
[7, 4, 2]
[8, 5, 3]


In [ ]:
#Q1. Write a NumPy program to convert Centigrade degrees into Fahrenheit
degrees. Centigrade values are stored in a NumPy array.
Sample Array [0, 12, 45.21, 34, 99.91]
[-17.78, -11.11, 7.34, 1.11, 37.73, 0. ]
Expected Output:
Values in Fahrenheit degrees:
[ 0. 12. 45.21 34. 99.91 32. ]

In [18]:
import numpy as np
c1=np.array([0, 12, 45.21, 34, 99.91])
c2=np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])
def convert(c):
    return np.append(c,32)
f1=convert(c1)
print("Values in Fahrenheit degrees:")
print(f1)

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91 32.  ]


In [14]:
import numpy as np
c1=np.array([0, 12, 45.21, 34, 99.91])
c2=np.array([-17.78, -11.11, 7.34, 1.11, 37.73, 0. ])
def convert(c):
   return (c*9/5)+32
f1=convert(c1)
f2=convert(c2)
print(c1)
print(f1)
print(f2)
print(c2)

[ 0.   12.   45.21 34.   99.91]
[ 32.     53.6   113.378  93.2   211.838]
[-4.0000e-03  1.2002e+01  4.5212e+01  3.3998e+01  9.9914e+01  3.2000e+01]
[-17.78 -11.11   7.34   1.11  37.73   0.  ]


In [20]:
# Q2. Write a NumPy program to find the number of elements in an array. It also
# finds the length of one array element in bytes and the total bytes consumed by
# the elements.
# Expected Output:
# Size of the array: 3
# Length of one array element in bytes: 8
# Total bytes consumed by the elements of the array:24


In [30]:
import numpy as np
a=np.array([10,20,30],dtype=np.int64)
b=a.size               
c=a.itemsize
d=a.nbytes #a*c=d
print(f"Size of the array:{b}")
print(f"Length of one array element in bytes:{c}")
print(f"Total bytes consumed by the elements of the array:{d}")
# int32 → 4 bytes
# int64 → 8 bytes
# float64 → 8 bytes

Size of the array:3
Length of one array element in bytes:8
Total bytes consumed by the elements of the array:24


In [58]:
# 3. Write a NumPy program to test whether each element of a 1-D array is
# also present in a second array.
def fun(a1,a2):
    a3=[]
    for i in a1:
        if i in a2:
            a3.append(True)
        else:
            a3.append(False)
    return a3
a1=np.array([0,10,20,40,60])
a2=np.array([0,40])
fun(a1,a2)

[True, False, False, True, False]

In [66]:
def fun(a1,a2):
    result=np.isin(a1,a2)
    return result
a1=np.array([0,10,20,40,60])
a2=np.array([0,40])
print(fun(a1,a2))

[ True False False  True False]


In [70]:
import numpy as np
a1=np.array([0,10,20,40,60])
a2=np.array([0,40])
result=np.array([i in a2 for i in a1])
print(result)  # Ensure single-line output

[ True False False  True False]


In [71]:
a1=np.array([0,10,20,40,60])
a2=np.array([0,40])
result=np.array(list(map(lambda i: i in a2 )))
result=np.array(list(map(lambda i: i in a2, a1)))
print(result)

[ True False False  True False]


In [9]:
import numpy as np
# Q4. Write a NumPy program to find common values between two arrays.
# Expected Output:
# Array1: [ 0 10 20 40 60]
# Array2: [10, 30, 40]
b1=np.array([0,10,20,40,60])
b2=np.array([10,30,40])
b3=[]
for i in b1:
    if i in b2:
        b3.append(i)
print(b3)

[10, 40]


In [14]:
b1=np.array([0,10,20,40,60])
b2=np.array([10,30,40])
b3=np.intersect1d(b1,b2)
print(b3)

[10 40]


In [23]:
#Q5.Write a NumPy program to get the unique elements of an array.
a11=np.array([10,10,20,20,30,30])
a22=np.array([[1,1],[2,3]])
print(np.unique(a11))
print(np.unique(a22))

[10 20 30]
[1 2 3]


In [25]:
a11=np.array([10,10,20,20,30,30])
a=[]
for i in a11:
    if i not in a:
        a.append(i)
r=np.array(a)
print(r)

[10 20 30]


In [32]:
a22=np.array([[1,1],[2,3]])
b=[]
for rose in a22:
    for col in rose:
       b.append(col)
r=np.array(b)
print(r)

[1 1 2 3]


In [38]:
# Q6. Write a NumPy program to find the union of two arrays. Union will return a
# unique, sorted array of values in each of the two input arrays.
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70]
# Unique sorted array of values that are in either of the two input arrays:
# [ 0 10 20 30 40 50 60 70 80]
a=np.array([0,10,20,40,60,80])
b=np.array([10,30,40,50,70])
c=list(a)+list(b)
d=[]
for i in c:
    if i not in d:
        d.append(i)
r=np.array(d)
print(sorted(r))

[0, 10, 20, 30, 40, 50, 60, 70, 80]


In [36]:
a=np.array([0,10,20,40,60,80])
b=np.array([10,30,40,50,70])
print(list(a)+list(b))

[0, 10, 20, 40, 60, 80, 10, 30, 40, 50, 70]


In [44]:
# Q7. Write a NumPy program to construct an array by repeating.
# Sample array: [1, 2, 3, 4]
a=np.array([1,2,3,4])
b=[]
for i in a:
   if i not in b:
        b.append(i)
r=np.array(b+b)
r1=np.array(b+b+b)
print(r)
print(r1)

[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


In [2]:
import numpy as np


In [62]:
#8
a=np.array([[4,6],[2,1]])
b=np.sort(a,axis=0)
c=np.sort(a,axis=1)
print(b)
print(c)

[[2 1]
 [4 6]]
[[4 6]
 [1 2]]


In [68]:
#9
first_names=np.array(["Betsey", "Shelley", "Lanell", "Genesis", "Margery"])
last_names=np.array(["Battle", "Brien", "Plotner", "Stahl", "Woolum"])
result=np.argsort(last_names)
print(result)

[0 1 2 3 4]


In [5]:
#10
z=np.zeros((1,2))
print(z)

[[0. 0.]]


In [6]:
z=np.zeros((1,2))
z

array([[0., 0.]])

In [12]:
#10
o=np.ones((1,2))
o

array([[1., 1.]])

In [11]:
o=np.ones((1,2))
inte=o.astype(int)
print(inte)

[[1 1]]


In [69]:
#11 
a=np.array([1,2,3,4,5,6,7,8,9])


In [72]:
c=a.reshape(3,3)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
#12
w=np.array([[10,20,30],[20,40,50]])
r=w.flatten()
print(r)

[10 20 30 20 40 50]


In [80]:
#13
a12=np.array([[1,2,3],[4,5,6]])
a12

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
r1=np.shape(a12)

In [82]:
r1

(2, 3)

In [83]:
r2=a12.dtype

In [78]:
r2

dtype('int32')

In [85]:
#14
x=np.full((3,5),2)
x

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [88]:
#15
v=np.array([[2,4,6],[6,8,10]])
print(v)

[[ 2  4  6]
 [ 6  8 10]]


In [89]:
v1=v.flatten()[2]

In [90]:
v1

6

In [48]:
#16
arr1=np.array([[0,1,3],[5,7,9]])
arr2 = np.array([[0,2,4],[6,8,10]])
result=np.concatenate((arr1,arr2),axis=1)
print(result)


[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [49]:
#17
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14])
a[:2]

array([1, 2])

In [52]:
a[2:6]


array([3, 4, 5, 6])

In [54]:
a[6::]

array([ 7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
#18
s=np.arange(1,100)
s=s[(s%3==0)|(s%5==0)]
print(s)
print(sum(s))

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [94]:
#19 this work on array
a12=np.array([1,2,3,4])
a13=np.array(['red','green','white','orange'])
a14=np.array([12.20,15,20,40])
result=zip(a12,a13,a14)
for i in result:
    print(i)

(1, 'red', 12.2)
(2, 'green', 15.0)
(3, 'white', 20.0)
(4, 'orange', 40.0)


In [95]:
#this is wprk on list only
a=[1,2,3,4]
b=['red','green','white','orange']
c=[12.20,15,20,40]
for i in range(len(a)):
    print((a[i], b[i], c[i]))

(1, 'red', 12.2)
(2, 'green', 15)
(3, 'white', 20)
(4, 'orange', 40)


In [20]:
#20
l=np.array([[0,1],[2,3],[4,5]])
r34=l.tolist()
print(r34)

[[0, 1], [2, 3], [4, 5]]
